author: Jake Ross
title: Geochronology of Southern McMurdo Sound and development of a 
 micro laser furnace 
degree: Doctor of Philosophy
 
grad_date: April, 2014
chair: William C. McIntosh
committee_size: 5

dedication: To my arrow... 
refs: ../src/data/andrill/andrill, 
 ../src/data/minna_bluff/minna_bluff,
 ../src/data/diode/pychron,
 ../src/data/pychron/pychron

abstract: abstract
keywords: Antarctica; Ar-Ar geochronology; Python

acknowledgments: Argon Lab, advisors. 
preface: Foo

body:
 - 
  - andrill
  - 
    - "Development of an age-depth model for ANDRILL MIS AND-1B drill core, McMurdo Sound, Antarctica"
 - 
  - minna_bluff 
  -
   - "Geochronology of Minna Bluff, Southern McMurdo Sound, Antartica"
   -
    - Introduction|intro
    - Geology
    -
     - Volcanic|volcanic
     - Glacial|glacial
    - Methods
    -
     - Ar-Ar
    - Results
    -
     - Ar-Ar Laser Fusion
     - Ar-Ar Step Heating
    - Discussion
 - 
  - diode
  - 
   - "Development and Testing of a laser micro furnace for Ar-Ar analysis"
   - 
    - Design
    - Testing
    - Preliminary Results
 - 
  - pychron
  -
   - "Pychron: Noble gas data acquisition and processing framework"
   
appendices:
 - Ar-Ar data
 - Electron Microprobe data
  
